/*
 * Copyright (c) 2012-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.terracottatech.store.function;

import java.util.Comparator;
import java.util.function.ToDoubleFunction;

import static java.lang.Double.doubleToLongBits;
import static java.util.Comparator.comparingDouble;

/**
 * A function of one argument that generates a {@code double} result, and
 * supports building derived functional types.
 *
 * @author Chris Dennis
 */
public interface BuildableToDoubleFunction<T> extends ToDoubleFunction<T> {

  /**
   * Returns a function that calculates the sum of {@code operand} and
   * {@code this}.
   *
   * @param operand the value to add
   * @return a summing function
   */
  default BuildableToDoubleFunction<T> add(double operand) {
    return t -> applyAsDouble(t) + operand;
  }

  /**
   * Returns a function that subtracts {@code operand} from {@code this}.
   *
   * @param operand the value to subtract
   * @return a subtracting function
   */
  default BuildableToDoubleFunction<T> subtract(double operand) {
    return add(-operand);
  }

  /**
   * Returns a function that increments {@code this} by one.
   *
   * @return an incrementing function
   */
  default BuildableToDoubleFunction<T> increment() {
    return add(1.0);
  }

  /**
   * Returns a function that decrements {@code this} by one.
   *
   * @return a decrementing function
   */
  default BuildableToDoubleFunction<T> decrement() {
    return subtract(1.0);
  }

  /**
   * Returns a function that calculates the product of {@code this} and
   * {@code multiplier}.
   *
   * @param multiplier the multiplier
   * @return a multiplying function
   */
  default BuildableToDoubleFunction<T> multiply(double multiplier) {
    return t -> applyAsDouble(t) * multiplier;
  }

  /**
   * Returns a function that calculates the quotient of {@code this} and
   * {@code divisor}.
   *
   * @param divisor the divisor
   * @return a dividing function
   */
  default BuildableToDoubleFunction<T> divide(double divisor) {
    return t -> applyAsDouble(t) / divisor;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} for
   * <em>equality</em> with the supplied constant.
   * <p>
   * This method uses the modified {@link Double#equals(Object)} contract
   * where {@code Double.NaN == Double.NaN}.
   *
   * @param test value to test against
   * @return an equality predicate
   */
  default BuildablePredicate<T> is(double test) {
    long bits = doubleToLongBits(test);
    return t -> doubleToLongBits(applyAsDouble(t)) == bits;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>greater than</em> the supplied constant.
   *
   * @param test value to test against
   * @return a greater than predicate
   */
  default BuildablePredicate<T> isGreaterThan(double test) {
    return t -> applyAsDouble(t) > test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>less than</em> the supplied constant.
   *
   * @param test value to test against
   * @return a less than predicate
   */
  default BuildablePredicate<T> isLessThan(double test) {
    return t -> applyAsDouble(t) < test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>greater than or equal to</em> the supplied constant.
   *
   * @param test value to test against
   * @return a greater than or equal to predicate
   */
  default BuildablePredicate<T> isGreaterThanOrEqualTo(double test) {
    return t -> applyAsDouble(t) >= test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>less than or equal to</em> the supplied constant.
   *
   * @param test value to test against
   * @return a less than or equal to predicate
   */
  default BuildablePredicate<T> isLessThanOrEqualTo(double test) {
    return t -> applyAsDouble(t) <= test;
  }

  /**
   * Returns a {@code Comparator} that orders objects using the double values
   * mapped by this function.
   *
   * @return a comparator that orders using the mapped values
   */
  default Comparator<T> asComparator() {
    return comparingDouble(this);
  }

  default BuildableComparableFunction<T, Double> boxed() {
    return this::applyAsDouble;
  }
}
