/*
 * Copyright (c) 2012-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.terracottatech.store.function;

import com.terracottatech.store.Type;
import com.terracottatech.store.internal.function.Functions;

import java.util.function.Function;

/**
 * A function of one argument that supports building derived functional types.
 *
 * @author Chris Dennis
 */
public interface BuildableFunction<T, R> extends Function<T, R> {

  /**
   * Returns a predicate that tests the value generated by {@code this} for
   * <em>equality</em> with the supplied constant.
   * <p>
   * Equality is defined by the behavior of the
   * {@link Type#equals(java.lang.Object, java.lang.Object)} method.
   *
   * @param test value to test against
   * @return an equality predicate
   */
  default BuildablePredicate<T> is(R test) {
    return t -> Type.equals(apply(t), test);
  }

  /**
   * Returns a function that simply returns its argument.
   * @param <T> the type of the input and resul
   * @return a function returning its argument
   */
  static <T> Function<T, T> identity() {
    return Functions.identityFunction();
  }
}
