/*
 * Copyright (c) 2012-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.terracottatech.store.function;

import java.util.Comparator;
import java.util.function.ToLongFunction;

import static java.util.Comparator.comparingLong;

/**
 * A function of one argument that generates a {@code long} result, and
 * supports building derived functional types.
 *
 * @author Chris Dennis
 */
public interface BuildableToLongFunction<T> extends ToLongFunction<T> {

  /**
   * Returns a function that calculates the sum of {@code operand} and
   * {@code this}.
   *
   * @param operand the value to add
   * @return a summing function
   */
  default BuildableToLongFunction<T> add(long operand) {
    return t -> applyAsLong(t) + operand;
  }

  /**
   * Returns a function that subtracts {@code operand} from {@code this}.
   *
   * @param operand the value to subtract
   * @return a subtracting function
   */
  default BuildableToLongFunction<T> subtract(long operand) {
    return add(-operand);
  }

  /**
   * Returns a function that increments {@code this} by one.
   *
   * @return an incrementing function
   */
  default BuildableToLongFunction<T> increment() {
    return add(1L);
  }

  /**
   * Returns a function that decrements {@code this} by one.
   *
   * @return a decrementing function
   */
  default BuildableToLongFunction<T> decrement() {
    return subtract(1L);
  }

  /**
   * Returns a function that calculates the product of {@code this} and
   * {@code multiplier}.
   *
   * @param multiplier the multiplier
   * @return a multiplying function
   */
  default BuildableToLongFunction<T> multiply(long multiplier) {
    return t -> applyAsLong(t) * multiplier;
  }

  /**
   * Returns a function that calculates the quotient of {@code this} and
   * {@code divisor}.
   *
   * @param divisor the divisor
   * @return a dividing function
   */
  default BuildableToLongFunction<T> divide(long divisor) {
    return t -> applyAsLong(t) / divisor;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} for
   * <em>equality</em> with the supplied constant.
   *
   * @param test value to test against
   * @return an equality predicate
   */
  default BuildablePredicate<T> is(long test) {
    return t -> applyAsLong(t) == test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>greater than</em> the supplied constant.
   *
   * @param test value to test against
   * @return a greater than predicate
   */
  default BuildablePredicate<T> isGreaterThan(long test) {
    return t -> applyAsLong(t) > test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>less than</em> the supplied constant.
   *
   * @param test value to test against
   * @return a less than predicate
   */
  default BuildablePredicate<T> isLessThan(long test) {
    return t -> applyAsLong(t) < test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>greater than or equal to</em> the supplied constant.
   *
   * @param test value to test against
   * @return a greater than or equal to predicate
   */
  default BuildablePredicate<T> isGreaterThanOrEqualTo(long test) {
    return t -> applyAsLong(t) >= test;
  }

  /**
   * Returns a predicate that tests the value generated by {@code this} to see
   * if it is <em>less than or equal to</em> the supplied constant.
   *
   * @param test value to test against
   * @return a less than or equal to predicate
   */
  default BuildablePredicate<T> isLessThanOrEqualTo(long test) {
    return t -> applyAsLong(t) <= test;
  }

  /**
   * Returns a {@code Comparator} that orders objects using the double values
   * mapped by this function.
   *
   * @return a comparator that orders using the mapped values
   */
  default Comparator<T> asComparator() {
    return comparingLong(this);
  }

  default BuildableComparableFunction<T, Long> boxed() {
    return this::applyAsLong;
  }
}
