/*
 * Copyright (c) 2012-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.terracottatech.store.function;

import static com.terracottatech.store.internal.function.GatedPredicate.gated;

/**
 * A function of one argument that generates an {@code Optional<String>} result, and
 * supports building derived functional types.
 *
 * @author Chris Dennis
 */
public interface BuildableStringOptionalFunction<T> extends BuildableComparableOptionalFunction<T, String> {

  //TODO : Make describable

  /**
   * Returns a function that maps the length of the extracted strings.
   *
   * @return a string length function
   */
  default BuildableComparableOptionalFunction<T, Integer> length() {
    return t -> apply(t).map(String::length);
  }

  /**
   * Returns a predicate that tests the strings generated by {@code this} to see
   * if they start with the supplied constant string. If {@code this} is a function
   * that generates an empty {@code Optional}, the returned predicate would always
   * evaluate to false
   *
   * @param prefix constant prefix string
   * @return a prefix predicate
   */
  default BuildablePredicate<T> startsWith(String prefix) {
    return gated(t -> apply(t).isPresent(), t -> apply(t).get().startsWith(prefix));
  }
}
