/*
 * Copyright (c) 2012-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Contains a set of types that form a DSL that allows the creation of behaviorally transparent
 * functions.
 * <p>
 *   Behaviorally transparent functions can be more readily and flexibly optimized.  The classes will normally be
 *   generated by accessing them through the DSL access points in:
 *   <ul>
 *     <li>{@link com.terracottatech.store.definition.CellDefinition} instances (and subtypes)</li>
 *     <li>{@link com.terracottatech.store.Record} instances</li>
 *     <li>{@link com.terracottatech.store.UpdateOperation} static methods</li>
 *     <li>{@link com.terracottatech.store.function.Collectors} static method</li>
 *   </ul>
 */
package com.terracottatech.store.function;
